"""
Topos Quantum Theory: The Doering-Isham Spectral Presheaf for a Single Qubit
=============================================================================

We explicitly construct the ENTIRE topos-theoretic structure for the
simplest quantum system: a single qubit (2x2 matrix algebra M_2(C)).

This makes the abstract theory concrete and computable:
- The context category V(M_2(C))
- The spectral presheaf Sigma
- Daseinisation of projections
- Truth values in the Heyting algebra Omega

References:
  [1] Doering & Isham, J. Math. Phys. 49 (2008), 053515-053518
  [2] Heunen, Landsman, Spitters, Commun. Math. Phys. 291 (2009), 63-110
  [3] Flori, "A First Course in Topos Quantum Theory", Springer (2013)

Wright Brothers, 2026
"""

import numpy as np
from itertools import product

print("=" * 70)
print("  TOPOS QUANTUM THEORY: SINGLE QUBIT (M_2(C))")
print("  A complete, explicit construction")
print("=" * 70)

# ============================================================================
#  PART 1: The Context Category V(M_2(C))
# ============================================================================
#
# The algebra of observables for a qubit is M_2(C) (2x2 complex matrices).
# A "context" V is a commutative *-subalgebra of M_2(C).
#
# For M_2(C), the contexts are:
#   - The trivial subalgebra: V_0 = C*I (scalar multiples of identity)
#   - For each unit vector n = (nx,ny,nz) on the Bloch sphere:
#     V_n = {a*I + b*(n.sigma) : a,b in C}
#     where n.sigma = nx*sigma_x + ny*sigma_y + nz*sigma_z
#
# V_n is the algebra generated by the spin observable in direction n.
# It is isomorphic to C^2 (two eigenvalues).
#
# The poset structure: V_0 ⊂ V_n for all n.
# No V_n is contained in another V_m (for n ≠ m).
#
# So V(M_2(C)) looks like a "fan":
#
#       V_z    V_x    V_y    V_{...}
#        \      |      /      /
#         \     |     /      /
#          \    |    /      /
#           \   |   /      /
#             V_0
#              (bottom)

print("\n--- PART 1: Context Category V(M_2(C)) ---")
print()
print("Contexts (commutative subalgebras):")
print("  V_0 = C*I  (trivial, bottom element)")
print("  V_n = span{I, n.sigma} for each direction n on Bloch sphere")
print()
print("  Poset structure: V_0 < V_n for all n")
print("                   V_n and V_m are incomparable for n != m")
print()
print("  This is a 'fan' or 'bouquet' shape:")
print("        V_z   V_x   V_y   V_45  ...")
print("         \\     |     /     /")
print("          \\    |    /     /")
print("           \\   |   /     /")
print("              V_0")

# ============================================================================
#  PART 2: The Spectral Presheaf Sigma
# ============================================================================
#
# The spectral presheaf assigns to each context V its Gelfand spectrum:
#
#   Sigma(V_0) = {*}       (one point - the trivial character)
#   Sigma(V_n) = {λ_+, λ_-}  (two points - the two eigenvalues ±1)
#
# The restriction maps (for V_0 ⊂ V_n):
#   Sigma(V_n) → Sigma(V_0):  both λ_+ and λ_- map to *
#
# So the spectral presheaf looks like:
#
#   {+,-}  {+,-}  {+,-}  {+,-}   <- Sigma(V_n) = two points each
#     \\      |      /      /
#      \\     |     /      /      <- all collapse to single point
#       \\    |    /      /
#          {*}                    <- Sigma(V_0) = one point

print("\n--- PART 2: Spectral Presheaf Sigma ---")
print()
print("  Sigma(V_0) = {*}         (trivial: one point)")
print("  Sigma(V_n) = {lam_+, lam_-}  (Gelfand spectrum: two eigenvalues)")
print()
print("  Restriction maps: Sigma(V_n) -> Sigma(V_0)")
print("    lam_+ |-> *")
print("    lam_- |-> *")
print()
print("  The spectral presheaf is a 'bundle of 2-point spaces over a fan'.")
print("  This is the GENERALIZED STATE SPACE of the qubit in the topos.")

# ============================================================================
#  PART 3: Daseinisation of Projections
# ============================================================================
#
# A quantum proposition "spin-z is up" corresponds to the projection:
#   P_z_up = |↑⟩⟨↑| = (1/2)(I + sigma_z) = [[1,0],[0,0]]
#
# Daseinisation approximates this projection in each context:
#
#   delta(P_z_up)(V_n) = "smallest projection in V_n that is >= P_z_up"
#                      = the "outer daseinisation"
#
# For V_z:  delta(P)(V_z) = P_z_up itself (P is already in V_z)
# For V_0:  delta(P)(V_0) = I (only projection in V_0 >= P is identity)
# For V_n (n != z): delta(P)(V_n) depends on angle between n and z:
#   If n.z > 0: delta(P)(V_n) = P_n_up = (1/2)(I + n.sigma)
#   If n.z < 0: delta(P)(V_n) = I (no proper projection >= P)
#   If n.z = 0: delta(P)(V_n) = I (e.g., V_x: spin-x doesn't dominate spin-z)

print("\n--- PART 3: Daseinisation ---")
print()
print("  Proposition: 'spin-z is up'")
print("  Projection:  P = |up><up| = (I + sigma_z)/2")
print()

# Concrete computation
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
I2 = np.eye(2, dtype=complex)

P_z_up = (I2 + sigma_z) / 2  # |↑⟩⟨↑|

def projection_in_direction(n):
    """Projection onto spin-up along direction n = (nx, ny, nz)."""
    nx, ny, nz = n
    return (I2 + nx * sigma_x + ny * sigma_y + nz * sigma_z) / 2

def daseinise(P, n):
    """
    Outer daseinisation of projection P in context V_n.
    Returns the smallest projection in V_n that is >= P.

    In V_n, the projections are: 0, P_n_up, P_n_down, I.
    We need the smallest among {P_n_up, P_n_down, I} that >= P.
    Q >= P iff P*Q = P (equivalently, range(P) ⊆ range(Q)).
    """
    P_n_up = projection_in_direction(n)
    P_n_down = I2 - P_n_up

    # Check P_n_up >= P
    diff_up = P_n_up - P
    eigenvalues_up = np.linalg.eigvalsh(diff_up)
    up_dominates = np.all(eigenvalues_up >= -1e-10)

    # Check P_n_down >= P
    diff_down = P_n_down - P
    eigenvalues_down = np.linalg.eigvalsh(diff_down)
    down_dominates = np.all(eigenvalues_down >= -1e-10)

    if up_dominates and down_dominates:
        # Both dominate; return the smaller one (lower trace)
        if np.trace(P_n_up).real <= np.trace(P_n_down).real:
            return P_n_up, "P_n_up"
        else:
            return P_n_down, "P_n_down"
    elif up_dominates:
        return P_n_up, "P_n_up"
    elif down_dominates:
        return P_n_down, "P_n_down"
    else:
        return I2, "I"

# Test daseinisation for various directions
directions = {
    "z  = (0,0,1) ": (0, 0, 1),
    "-z = (0,0,-1)": (0, 0, -1),
    "x  = (1,0,0) ": (1, 0, 0),
    "y  = (0,1,0) ": (0, 1, 0),
    "45 = (0,s,s) ": (0, 1/np.sqrt(2), 1/np.sqrt(2)),
    "135= (0,s,-s)": (0, 1/np.sqrt(2), -1/np.sqrt(2)),
}

print("  Daseinisation of P_z_up in each context V_n:")
print("  " + "-" * 55)
for name, n in directions.items():
    _, label = daseinise(P_z_up, n)
    angle = np.arccos(np.clip(n[2], -1, 1)) * 180 / np.pi
    print(f"    V_{name}: delta(P)(V_n) = {label:8s}  (angle from z: {angle:.0f} deg)")

print()
print("  Interpretation:")
print("    - In V_z: P_z_up is EXACTLY the proposition (no approximation)")
print("    - In V_45: P_45_up dominates P_z_up (45 deg cone contains z-up)")
print("    - In V_x: neither P_x_up nor P_x_down dominates P_z_up")
print("      => daseinisation falls back to I (trivially true)")
print("    - In V_{-z}: P_{-z}_down = P_z_up, so it works")
print()
print("  THIS IS CONTEXTUALITY made mathematically precise:")
print("  The 'truth' of 'spin-z is up' depends on which context you're in.")

# ============================================================================
#  PART 4: Truth Values in the Heyting Algebra
# ============================================================================
#
# In the topos Set^{V(N)^op}, the subobject classifier Omega assigns
# to each context V the set of "sieves" on V:
#
#   Omega(V) = {S ⊆ ↓V : S is a sieve}
#
# where ↓V = {W ∈ V(N) : W ⊆ V}.
#
# For our fan-shaped poset:
#   ↓V_0 = {V_0}
#   ↓V_n = {V_0, V_n}
#
# Sieves on V_n: subsets S of {V_0, V_n} that are downward-closed:
#   S = {}        (empty sieve → "totally false")
#   S = {V_0}     (partial truth: true at V_0 but not V_n)
#   S = {V_0, V_n} (maximal sieve → "totally true")
#
# Wait - {V_0} is not a sieve on V_n because it's not downward-closed
# with respect to the arrow V_0 → V_n. Actually, sieves on V in the
# category V(N)^op consist of all W ≥ V such that... Let me be precise.
#
# A sieve on V in V(N)^op is a set S of morphisms TO V (in V(N)^op),
# i.e., inclusions V ⊆ W in V(N), that is closed under precomposition.
#
# For V_n: arrows to V_n in V(N)^op = inclusions V_n ⊆ W in V(N).
# Since V_n is maximal, the only arrow is id: V_n → V_n.
# So Omega(V_n) = {empty, {id}} = {0, 1} ≅ {false, true}.
#
# For V_0: arrows to V_0 in V(N)^op = inclusions V_0 ⊆ W in V(N).
# These are: V_0 ⊆ V_0, V_0 ⊆ V_x, V_0 ⊆ V_y, V_0 ⊆ V_z, ...
# A sieve S on V_0 is a subset closed under precomposition.
# For our fan: a sieve on V_0 is determined by which V_n's it contains.
#
# For a finite set of contexts {V_0, V_x, V_y, V_z}:
# Omega(V_0) has elements corresponding to subsets of {V_x, V_y, V_z} plus V_0.

print("\n--- PART 4: Truth Values (Heyting Algebra) ---")
print()
print("  In the topos, truth values are NOT just {true, false}.")
print("  They form a HEYTING ALGEBRA (intuitionistic logic).")
print()

# For concreteness, work with 3 contexts: V_x, V_y, V_z (plus V_0)
contexts = ['V_x', 'V_y', 'V_z']

print("  For the qubit with contexts {V_0, V_x, V_y, V_z}:")
print()
print("  At maximal contexts V_n: truth values = {0, 1} (Boolean)")
print("  At V_0: truth values = subsets of {V_x, V_y, V_z} = 2^3 = 8 values")
print()
print("  The 8 truth values at V_0:")
for i in range(8):
    subset = [c for j, c in enumerate(contexts) if i & (1 << j)]
    label = "{" + ", ".join(subset) + "}" if subset else "{}"
    print(f"    {i}: {label}")

print()
print("  This is a HEYTING ALGEBRA (distributive lattice with implication).")
print("  The law of excluded middle FAILS:")
print("    For truth value {V_x} at V_0:")
print("      {V_x} OR NOT({V_x}) = {V_x} OR {V_y, V_z} = {V_x, V_y, V_z}")
print("      ≠ {V_x, V_y, V_z} = top  ✓ (here it works)")
print("    But the Heyting negation is NOT the set complement in general!")
print("    NOT({V_x}) = largest S such that S AND {V_x} = empty = {V_y, V_z}")
print()
print("  The PHYSICAL meaning:")
print("    Truth value {V_z} means: 'this proposition is true in context V_z")
print("    but not in V_x or V_y.' This is CONTEXTUALITY expressed as")
print("    a many-valued truth assignment.")

# ============================================================================
#  PART 5: The Truth Value of "Spin-z is Up" in State |↑⟩
# ============================================================================

print("\n--- PART 5: Computing a Physical Truth Value ---")
print()
print("  State: |up> (spin-z eigenstate)")
print("  Proposition: 'spin-z is up'")
print("  Projection: P = |up><up|")
print()

# The truth value is computed by:
# For each context V_n, check if the state |↑⟩ "makes the daseinised
# proposition true" at V_n.
#
# At V_n: the daseinised proposition delta(P)(V_n) is a clopen subset
# of Sigma(V_n). The state |↑⟩ defines a "pseudo-state" (not a global
# section of Sigma, but a natural transformation).
#
# For a pure state |ψ⟩, the truth value at context V_n is:
#   ⟨ψ| delta(P)(V_n) |ψ⟩ = 1  →  V_n is in the truth value sieve
#   ⟨ψ| delta(P)(V_n) |ψ⟩ < 1  →  V_n is NOT in the sieve

psi = np.array([1, 0], dtype=complex)  # |↑⟩

print("  Truth value sieve (which contexts make the proposition true):")
print("  " + "-" * 50)
truth_sieve = []
for name, n in directions.items():
    D, label = daseinise(P_z_up, n)
    expectation = np.real(psi.conj() @ D @ psi)
    in_sieve = np.isclose(expectation, 1.0)
    truth_sieve.append((name, in_sieve))
    status = "IN SIEVE (true)" if in_sieve else "not in sieve"
    print(f"    V_{name}: <up|delta(P)(V)|up> = {expectation:.3f}  -> {status}")

print()
print("  Result: The truth value of 'spin-z is up' in state |up> is")
print("  NOT simply 'true'. It is a SIEVE - a set of contexts where")
print("  the proposition holds after daseinisation.")
print()
print("  In contexts aligned with z: TRUE (expectation = 1)")
print("  In contexts perpendicular to z: TRIVIALLY TRUE (daseinisation -> I)")
print("  In contexts anti-aligned with z: also TRUE (P_{-z}_down = P_z_up)")
print()
print("  THIS is topos quantum logic: propositions have nuanced,")
print("  context-dependent truth values - not just true/false.")

# ============================================================================
#  PART 6: The Kochen-Specker Theorem - Why This Matters
# ============================================================================

print("\n--- PART 6: The Kochen-Specker Theorem in the Topos ---")
print()
print("  The Kochen-Specker theorem says:")
print("    There is NO global section of the spectral presheaf Sigma.")
print("    (No way to assign a classical state to ALL contexts consistently.)")
print()
print("  Proof for the qubit:")
print("    A global section would assign to each V_n one of {lam_+, lam_-},")
print("    i.e., a function f: S^2 -> {+1, -1} (spin value for each direction)")
print("    such that f is continuous (compatible with restriction maps).")
print()
print("    But S^2 is connected, and {+1, -1} is discrete.")
print("    A continuous function S^2 -> {+1,-1} must be CONSTANT.")
print("    But spin-z up and spin-z down are different: contradiction!")
print()
print("  This is the TOPOLOGICAL content of Kochen-Specker.")
print("  The topos formulation makes it a statement about the")
print("  NON-EXISTENCE of global sections - a cohomological obstruction.")
print("  (cf. Abramsky-Brandenburger, New J. Phys. 2011)")

print()
print("  ============================================================")
print("  SUMMARY")
print("  ============================================================")
print("  We have explicitly constructed:")
print("    1. The context category V(M_2(C)) - a fan-shaped poset")
print("    2. The spectral presheaf Sigma - the 'generalized state space'")
print("    3. Daseinisation - approximating quantum propositions in contexts")
print("    4. The Heyting algebra of truth values - 8 values, not just 2")
print("    5. A physical truth value computation for |up> and P_z_up")
print("    6. Kochen-Specker as non-existence of global sections")
print()
print("  All of quantum mechanics' 'weirdness' (contextuality, complementarity,")
print("  non-commutativity) is captured as GEOMETRY in the topos.")
print("  The topos is the natural 'operating system' for quantum logic.")
