"""
Bost-Connes System: The Riemann Zeta Function as a Phase Transition
====================================================================

The Bost-Connes system (1995) is a quantum statistical mechanical system
whose partition function IS the Riemann zeta function ζ(β), and whose
symmetry-breaking at β=1 reveals the Galois group Gal(Q^ab/Q).

This is the most concrete evidence that number theory and quantum
statistical mechanics share the same deep structure.

References:
  [1] Bost & Connes, Selecta Math. 1 (1995), 411-457
  [2] Connes & Marcolli, "Noncommutative Geometry, Quantum Fields and Motives" (2008)

Wright Brothers, 2026
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import zeta as scipy_zeta

# ============================================================================
#  PART 1: The Partition Function Z(β) = ζ(β)
# ============================================================================
#
# The Bost-Connes C*-dynamical system (A, σ_t) has:
#   - Algebra A generated by operators μ_n (isometries) and e(r) (r ∈ Q/Z)
#   - Time evolution σ_t(μ_n) = n^{it} μ_n
#   - The partition function in the KMS formalism:
#
#       Z(β) = Tr(e^{-βH}) = Σ_{n=1}^∞ n^{-β} = ζ(β)
#
# This is literally the Riemann zeta function.

def zeta_truncated(beta, N_max=10000):
    """Compute ζ(β) = Σ_{n=1}^{N_max} n^{-β} by direct summation."""
    n = np.arange(1, N_max + 1, dtype=np.float64)
    return np.sum(n ** (-beta))

def partition_function(beta_array, N_max=10000):
    """Partition function Z(β) = ζ(β) for array of inverse temperatures."""
    return np.array([zeta_truncated(b, N_max) if b > 1.001 else np.nan
                     for b in beta_array])

# Compute Z(β) across the phase transition
beta = np.linspace(0.1, 5.0, 1000)
Z = partition_function(beta)

# ============================================================================
#  PART 2: Phase Transition at β = 1
# ============================================================================
#
# The Bost-Connes system has a phase transition at β = 1:
#
#   β < 1:  Unique KMS state (disordered / high temperature)
#           Free energy F = -T log Z → finite
#
#   β = 1:  CRITICAL POINT
#           ζ(1) diverges (pole of ζ)
#           This is the phase transition.
#
#   β > 1:  Spontaneous symmetry breaking!
#           Infinitely many extremal KMS states φ_{β,ρ}
#           parameterized by embeddings ρ: Q^ab → C
#           The symmetry group Gal(Q^ab/Q) acts on these states.
#
# Physical interpretation:
#   The "ordering" that emerges at low temperature IS the arithmetic
#   structure of the rational numbers. Number theory is literally
#   a symmetry-breaking phenomenon.

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Bost–Connes System: ζ(β) as Phase Transition\n'
             'ボスト-コンヌ系：相転移としてのζ関数',
             fontsize=14, fontweight='bold')

# --- Panel 1: Partition function Z(β) = ζ(β) ---
ax = axes[0, 0]
mask = beta > 1.01
ax.plot(beta[mask], Z[mask], color='#ffd93d', linewidth=2)
ax.axvline(x=1, color='#ff6b6b', linewidth=2, linestyle='--', alpha=0.8,
           label='β = 1 (critical point / 臨界点)')
ax.set_xlabel('β (inverse temperature / 逆温度)', fontsize=11)
ax.set_ylabel('Z(β) = ζ(β)', fontsize=11)
ax.set_title('Partition Function = Riemann Zeta / 分配関数 = リーマンζ', fontsize=11)
ax.set_ylim(0, 20)
ax.legend(fontsize=9)
ax.set_facecolor('#0a0a1a')
ax.grid(alpha=0.15)

# --- Panel 2: Free energy F(β) = -log Z(β) / β ---
ax = axes[0, 1]
F = -np.log(Z[mask]) / beta[mask]
ax.plot(beta[mask], F, color='#00d4ff', linewidth=2)
ax.axvline(x=1, color='#ff6b6b', linewidth=2, linestyle='--', alpha=0.8)
ax.set_xlabel('β', fontsize=11)
ax.set_ylabel('F(β) = -log Z(β) / β', fontsize=11)
ax.set_title('Free Energy / 自由エネルギー', fontsize=11)
ax.set_facecolor('#0a0a1a')
ax.grid(alpha=0.15)

# ============================================================================
#  PART 3: KMS States and Special Values ζ(n)
# ============================================================================
#
# For β > 1 (low temperature phase), the KMS states evaluated on the
# arithmetic generators give:
#
#   φ_β(e(0)) = ζ(β)^{-1} · Σ_{n=1}^∞ n^{-β} = 1   (normalization)
#
#   φ_β(μ_n μ_n*) = n^{-β} / ζ(β)    (occupation probability of level n)
#
# At integer β = k, these become:
#   φ_k(μ_n μ_n*) = n^{-k} / ζ(k)
#
# The special values ζ(2) = π²/6, ζ(4) = π⁴/90, etc. appear naturally.

ax = axes[1, 0]
# Occupation probabilities at different temperatures
for beta_val, color, label in [(2, '#ffd93d', 'β=2: ζ(2)=π²/6'),
                                 (3, '#00d4ff', 'β=3: ζ(3)≈1.202'),
                                 (4, '#ff6b6b', 'β=4: ζ(4)=π⁴/90'),
                                 (6, '#6bff8d', 'β=6: ζ(6)=π⁶/945')]:
    n_vals = np.arange(1, 21)
    Z_val = scipy_zeta(beta_val, 1)
    probs = n_vals.astype(float) ** (-beta_val) / Z_val
    ax.bar(n_vals + (beta_val - 3) * 0.15, probs, width=0.15,
           color=color, alpha=0.85, label=label)

ax.set_xlabel('n (energy level / エネルギー準位)', fontsize=11)
ax.set_ylabel('φ_β(μₙμₙ*) = n⁻ᵝ/ζ(β)', fontsize=11)
ax.set_title('KMS State Occupation / KMS状態の占有確率', fontsize=11)
ax.legend(fontsize=8)
ax.set_facecolor('#0a0a1a')
ax.grid(alpha=0.15)

# ============================================================================
#  PART 4: The Galois Symmetry — Gal(Q^ab/Q)
# ============================================================================
#
# The most remarkable feature: at β > 1, the extremal KMS states are
# parameterized by embeddings of Q^ab (maximal abelian extension of Q)
# into C. The Galois group Gal(Q^ab/Q) ≅ Ẑ* acts on these states by:
#
#   α · φ_{β,ρ} = φ_{β, ρ ∘ α^{-1}}
#
# By CLASS FIELD THEORY (Kronecker-Weber theorem):
#   Gal(Q^ab/Q) ≅ Ẑ* = ∏_p Z_p*
#
# This means: the arithmetic of ALL primes simultaneously appears
# as the symmetry group of the low-temperature phase.
#
# Visualization: action of Gal on roots of unity

ax = axes[1, 1]
# Roots of unity ζ_n = e^{2πi/n} for n = 1..12
# Galois action: σ_a(ζ_n) = ζ_n^a for a ∈ (Z/nZ)*
N = 12
theta = np.linspace(0, 2 * np.pi, 200)
ax.plot(np.cos(theta), np.sin(theta), color='white', alpha=0.15, linewidth=1)

# Plot all N-th roots
for k in range(N):
    angle = 2 * np.pi * k / N
    x, y = np.cos(angle), np.sin(angle)
    ax.plot(x, y, 'o', color='#ffd93d', markersize=8, zorder=5)
    ax.annotate(f'ζ₁₂^{k}', (x * 1.15, y * 1.15), fontsize=7,
                ha='center', va='center', color='#a0a0c0')

# Show Galois action σ_5: ζ_12 ↦ ζ_12^5
for k in range(N):
    if np.gcd(k, N) == k or k == 0:
        continue
    src = 2 * np.pi * k / N
    dst = 2 * np.pi * (5 * k % N) / N
    ax.annotate('', xy=(np.cos(dst) * 0.9, np.sin(dst) * 0.9),
                xytext=(np.cos(src) * 0.9, np.sin(src) * 0.9),
                arrowprops=dict(arrowstyle='->', color='#ff6b6b', lw=1.2, alpha=0.6))

ax.set_xlim(-1.5, 1.5)
ax.set_ylim(-1.5, 1.5)
ax.set_aspect('equal')
ax.set_title('Galois Action σ₅ on 12th Roots of Unity\n'
             'ガロア作用 σ₅ の12乗根への作用', fontsize=10)
ax.text(0, -1.35, 'Gal(Q^ab/Q) ≅ Ẑ* = symmetry of low-T phase',
        ha='center', fontsize=8, color='#a0a0c0', style='italic')
ax.set_facecolor('#0a0a1a')
ax.grid(alpha=0.1)

plt.tight_layout()
plt.savefig('research/01_bost_connes/bost_connes_phase_transition.png',
            dpi=150, bbox_inches='tight', facecolor='#0a0a1a')
plt.close()

print("=" * 70)
print("  BOST-CONNES SYSTEM: NUMERICAL RESULTS")
print("  ボスト-コンヌ系：数値結果")
print("=" * 70)

print("\n--- Special values of ζ(β) = Partition function Z(β) ---")
print(f"  ζ(2) = {scipy_zeta(2, 1):.10f}  (exact: π²/6 = {np.pi**2/6:.10f})")
print(f"  ζ(3) = {scipy_zeta(3, 1):.10f}  (Apéry's constant)")
print(f"  ζ(4) = {scipy_zeta(4, 1):.10f}  (exact: π⁴/90 = {np.pi**4/90:.10f})")
print(f"  ζ(6) = {scipy_zeta(6, 1):.10f}  (exact: π⁶/945 = {np.pi**6/945:.10f})")

print("\n--- Phase transition at β = 1 ---")
print(f"  ζ(1.01) = {zeta_truncated(1.01):.2f}  (approaching divergence)")
print(f"  ζ(1.001) = {zeta_truncated(1.001):.2f}")
print(f"  ζ(1.0001) = {zeta_truncated(1.0001):.2f}")
print(f"  → ζ(1) = ∞  (pole / 極)")
print(f"  This divergence IS the phase transition.")

print("\n--- KMS occupation probabilities at β = 2 ---")
Z2 = scipy_zeta(2, 1)
for n in [1, 2, 3, 4, 5, 10, 100]:
    prob = n ** (-2) / Z2
    print(f"  P(level {n:3d}) = {n}^(-2)/ζ(2) = {prob:.6f}")

print("\n--- Physical interpretation ---")
print("  β < 1: Unique KMS state (disordered, high temperature)")
print("         → No number-theoretic structure visible")
print("  β = 1: Phase transition (ζ diverges)")
print("         → Arithmetic structure begins to crystallize")
print("  β > 1: Symmetry breaking by Gal(Q^ab/Q)")
print("         → The primes 'order' the vacuum")
print("         → Arithmetic IS the low-temperature phase of physics")

print("\n--- Galois group structure ---")
print("  Gal(Q^ab/Q) ≅ Ẑ* = ∏_p Z_p*")
print("  This group acts on the KMS states at β > 1.")
print("  Each prime p contributes a factor Z_p* to the symmetry.")
print("  The symmetry of the NUMBER-THEORETIC vacuum is literally")
print("  the product over ALL PRIMES.")

print(f"\n  Plot saved: research/01_bost_connes/bost_connes_phase_transition.png")
